Line-edit user-facing text in remediation scripts
This commit makes minor improvements to all prompt text in the scripts
in bin/.

diff --git a/bin/pe_step5_migrate_the_master b/bin/pe_step5_migrate_the_master
--- a/bin/pe_step5_migrate_the_master
+++ b/bin/pe_step5_migrate_the_master
@@ -31,14 +31,14 @@ certname="$(puppet master --configprint certname)"
 # variable isn't already set.
 : ${DNS_NAME:=$(cat "${vardir}/${module}/dns_name")}
 if [[ -z "${DNS_NAME}" ]]; then
-  echo "Error: Could not determine the intermediate dns name from step1." >&2
-  echo "Did you run step1 first?" >&2
+  echo "Error: Could not determine the intermediate dns name from step 1." >&2
+  echo "Did you run step 1 first?" >&2
   exit 1
 fi
 : ${DNS_ALT_NAMES:=$(cat "${vardir}/${module}/alt_names")}
 if [[ -z "${DNS_ALT_NAMES}" ]]; then
-  echo "Error: Could not determine the certdnsnames from step1." >&2
-  echo "Did you run step1 first?" >&2
+  echo "Error: Could not determine the certdnsnames from step 1." >&2
+  echo "Did you run step 1 first?" >&2
   echo "If you do not want any alternate names in your new master certificate" >&2
   echo "simply touch ${vardir}/${module}/alt_names (Create an empty file)" >&2
   exit 1
@@ -72,10 +72,10 @@ echo -n "Starting Puppet Master..." >&2
 puppet resource service pe-httpd ensure=running hasstatus=true &> /dev/null
 echo "done." >&2
 
-cat <<-EOMESSAGE
+cat <<EOMESSAGE
 
-The puppet master has been issued a SSL certificate.  The migration to the new
-CA is now complete.  Puppet agents who have been migrated should now be able to
-reconnect to this master.
+The puppet master has been issued an SSL certificate by the new CA.  The
+migration to the new CA is now complete.  Puppet agents which have been migrated
+should now be able to reconnect to this master.
 
 EOMESSAGE
